name: BreakTheNexus
version: 1
author: Tyler Beringer
main: com.gmail._99tylerberinger.breakthenexus.BreakTheNexus
api-version: 1.8.8
commands:
  kit:
    description: kit commands
  team:
    description: team commands